// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GET.proto

#ifndef PROTOBUF_GET_2eproto__INCLUDED
#define PROTOBUF_GET_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace GET {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GET_2eproto();
void protobuf_AssignDesc_GET_2eproto();
void protobuf_ShutdownFile_GET_2eproto();

class TaskParam;
class AddParam;
class SubParam;
class MulParam;
class ConvParam;
class PoolParam;
class LRNParam;
class ReLUParam;
class SigmoidParam;

enum TaskParam_DataPosition {
  TaskParam_DataPosition_FILE = 0,
  TaskParam_DataPosition_HOSTMEM = 1
};
bool TaskParam_DataPosition_IsValid(int value);
const TaskParam_DataPosition TaskParam_DataPosition_DataPosition_MIN = TaskParam_DataPosition_FILE;
const TaskParam_DataPosition TaskParam_DataPosition_DataPosition_MAX = TaskParam_DataPosition_HOSTMEM;
const int TaskParam_DataPosition_DataPosition_ARRAYSIZE = TaskParam_DataPosition_DataPosition_MAX + 1;

const ::google::protobuf::EnumDescriptor* TaskParam_DataPosition_descriptor();
inline const ::std::string& TaskParam_DataPosition_Name(TaskParam_DataPosition value) {
  return ::google::protobuf::internal::NameOfEnum(
    TaskParam_DataPosition_descriptor(), value);
}
inline bool TaskParam_DataPosition_Parse(
    const ::std::string& name, TaskParam_DataPosition* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TaskParam_DataPosition>(
    TaskParam_DataPosition_descriptor(), name, value);
}
enum TaskParam_TaskType {
  TaskParam_TaskType_ADD = 0,
  TaskParam_TaskType_SUB = 1,
  TaskParam_TaskType_MULTI = 2,
  TaskParam_TaskType_CONVOLUTION = 3,
  TaskParam_TaskType_POOLING = 4,
  TaskParam_TaskType_LRN = 5,
  TaskParam_TaskType_RELU = 6,
  TaskParam_TaskType_Sigmoid = 7
};
bool TaskParam_TaskType_IsValid(int value);
const TaskParam_TaskType TaskParam_TaskType_TaskType_MIN = TaskParam_TaskType_ADD;
const TaskParam_TaskType TaskParam_TaskType_TaskType_MAX = TaskParam_TaskType_Sigmoid;
const int TaskParam_TaskType_TaskType_ARRAYSIZE = TaskParam_TaskType_TaskType_MAX + 1;

const ::google::protobuf::EnumDescriptor* TaskParam_TaskType_descriptor();
inline const ::std::string& TaskParam_TaskType_Name(TaskParam_TaskType value) {
  return ::google::protobuf::internal::NameOfEnum(
    TaskParam_TaskType_descriptor(), value);
}
inline bool TaskParam_TaskType_Parse(
    const ::std::string& name, TaskParam_TaskType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TaskParam_TaskType>(
    TaskParam_TaskType_descriptor(), name, value);
}
// ===================================================================

class TaskParam : public ::google::protobuf::Message {
 public:
  TaskParam();
  virtual ~TaskParam();

  TaskParam(const TaskParam& from);

  inline TaskParam& operator=(const TaskParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TaskParam& default_instance();

  void Swap(TaskParam* other);

  // implements Message ----------------------------------------------

  TaskParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TaskParam& from);
  void MergeFrom(const TaskParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TaskParam_DataPosition DataPosition;
  static const DataPosition FILE = TaskParam_DataPosition_FILE;
  static const DataPosition HOSTMEM = TaskParam_DataPosition_HOSTMEM;
  static inline bool DataPosition_IsValid(int value) {
    return TaskParam_DataPosition_IsValid(value);
  }
  static const DataPosition DataPosition_MIN =
    TaskParam_DataPosition_DataPosition_MIN;
  static const DataPosition DataPosition_MAX =
    TaskParam_DataPosition_DataPosition_MAX;
  static const int DataPosition_ARRAYSIZE =
    TaskParam_DataPosition_DataPosition_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  DataPosition_descriptor() {
    return TaskParam_DataPosition_descriptor();
  }
  static inline const ::std::string& DataPosition_Name(DataPosition value) {
    return TaskParam_DataPosition_Name(value);
  }
  static inline bool DataPosition_Parse(const ::std::string& name,
      DataPosition* value) {
    return TaskParam_DataPosition_Parse(name, value);
  }

  typedef TaskParam_TaskType TaskType;
  static const TaskType ADD = TaskParam_TaskType_ADD;
  static const TaskType SUB = TaskParam_TaskType_SUB;
  static const TaskType MULTI = TaskParam_TaskType_MULTI;
  static const TaskType CONVOLUTION = TaskParam_TaskType_CONVOLUTION;
  static const TaskType POOLING = TaskParam_TaskType_POOLING;
  static const TaskType LRN = TaskParam_TaskType_LRN;
  static const TaskType RELU = TaskParam_TaskType_RELU;
  static const TaskType Sigmoid = TaskParam_TaskType_Sigmoid;
  static inline bool TaskType_IsValid(int value) {
    return TaskParam_TaskType_IsValid(value);
  }
  static const TaskType TaskType_MIN =
    TaskParam_TaskType_TaskType_MIN;
  static const TaskType TaskType_MAX =
    TaskParam_TaskType_TaskType_MAX;
  static const int TaskType_ARRAYSIZE =
    TaskParam_TaskType_TaskType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  TaskType_descriptor() {
    return TaskParam_TaskType_descriptor();
  }
  static inline const ::std::string& TaskType_Name(TaskType value) {
    return TaskParam_TaskType_Name(value);
  }
  static inline bool TaskType_Parse(const ::std::string& name,
      TaskType* value) {
    return TaskParam_TaskType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .GET.TaskParam.DataPosition source_pos = 1 [default = HOSTMEM];
  inline bool has_source_pos() const;
  inline void clear_source_pos();
  static const int kSourcePosFieldNumber = 1;
  inline ::GET::TaskParam_DataPosition source_pos() const;
  inline void set_source_pos(::GET::TaskParam_DataPosition value);

  // repeated string sourcef = 2;
  inline int sourcef_size() const;
  inline void clear_sourcef();
  static const int kSourcefFieldNumber = 2;
  inline const ::std::string& sourcef(int index) const;
  inline ::std::string* mutable_sourcef(int index);
  inline void set_sourcef(int index, const ::std::string& value);
  inline void set_sourcef(int index, const char* value);
  inline void set_sourcef(int index, const char* value, size_t size);
  inline ::std::string* add_sourcef();
  inline void add_sourcef(const ::std::string& value);
  inline void add_sourcef(const char* value);
  inline void add_sourcef(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& sourcef() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_sourcef();

  // repeated uint64 sourcem = 3;
  inline int sourcem_size() const;
  inline void clear_sourcem();
  static const int kSourcemFieldNumber = 3;
  inline ::google::protobuf::uint64 sourcem(int index) const;
  inline void set_sourcem(int index, ::google::protobuf::uint64 value);
  inline void add_sourcem(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      sourcem() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_sourcem();

  // optional .GET.TaskParam.DataPosition result_pos = 4 [default = HOSTMEM];
  inline bool has_result_pos() const;
  inline void clear_result_pos();
  static const int kResultPosFieldNumber = 4;
  inline ::GET::TaskParam_DataPosition result_pos() const;
  inline void set_result_pos(::GET::TaskParam_DataPosition value);

  // repeated string resultf = 5;
  inline int resultf_size() const;
  inline void clear_resultf();
  static const int kResultfFieldNumber = 5;
  inline const ::std::string& resultf(int index) const;
  inline ::std::string* mutable_resultf(int index);
  inline void set_resultf(int index, const ::std::string& value);
  inline void set_resultf(int index, const char* value);
  inline void set_resultf(int index, const char* value, size_t size);
  inline ::std::string* add_resultf();
  inline void add_resultf(const ::std::string& value);
  inline void add_resultf(const char* value);
  inline void add_resultf(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& resultf() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_resultf();

  // repeated uint64 resultm = 6;
  inline int resultm_size() const;
  inline void clear_resultm();
  static const int kResultmFieldNumber = 6;
  inline ::google::protobuf::uint64 resultm(int index) const;
  inline void set_resultm(int index, ::google::protobuf::uint64 value);
  inline void add_resultm(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      resultm() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_resultm();

  // optional .GET.TaskParam.TaskType type = 7;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 7;
  inline ::GET::TaskParam_TaskType type() const;
  inline void set_type(::GET::TaskParam_TaskType value);

  // optional .GET.AddParam add_param = 8;
  inline bool has_add_param() const;
  inline void clear_add_param();
  static const int kAddParamFieldNumber = 8;
  inline const ::GET::AddParam& add_param() const;
  inline ::GET::AddParam* mutable_add_param();
  inline ::GET::AddParam* release_add_param();
  inline void set_allocated_add_param(::GET::AddParam* add_param);

  // optional .GET.SubParam sub_param = 9;
  inline bool has_sub_param() const;
  inline void clear_sub_param();
  static const int kSubParamFieldNumber = 9;
  inline const ::GET::SubParam& sub_param() const;
  inline ::GET::SubParam* mutable_sub_param();
  inline ::GET::SubParam* release_sub_param();
  inline void set_allocated_sub_param(::GET::SubParam* sub_param);

  // optional .GET.MulParam mul_param = 10;
  inline bool has_mul_param() const;
  inline void clear_mul_param();
  static const int kMulParamFieldNumber = 10;
  inline const ::GET::MulParam& mul_param() const;
  inline ::GET::MulParam* mutable_mul_param();
  inline ::GET::MulParam* release_mul_param();
  inline void set_allocated_mul_param(::GET::MulParam* mul_param);

  // optional .GET.ConvParam conv_param = 11;
  inline bool has_conv_param() const;
  inline void clear_conv_param();
  static const int kConvParamFieldNumber = 11;
  inline const ::GET::ConvParam& conv_param() const;
  inline ::GET::ConvParam* mutable_conv_param();
  inline ::GET::ConvParam* release_conv_param();
  inline void set_allocated_conv_param(::GET::ConvParam* conv_param);

  // optional .GET.PoolParam pool_param = 12;
  inline bool has_pool_param() const;
  inline void clear_pool_param();
  static const int kPoolParamFieldNumber = 12;
  inline const ::GET::PoolParam& pool_param() const;
  inline ::GET::PoolParam* mutable_pool_param();
  inline ::GET::PoolParam* release_pool_param();
  inline void set_allocated_pool_param(::GET::PoolParam* pool_param);

  // optional .GET.LRNParam lrn_param = 13;
  inline bool has_lrn_param() const;
  inline void clear_lrn_param();
  static const int kLrnParamFieldNumber = 13;
  inline const ::GET::LRNParam& lrn_param() const;
  inline ::GET::LRNParam* mutable_lrn_param();
  inline ::GET::LRNParam* release_lrn_param();
  inline void set_allocated_lrn_param(::GET::LRNParam* lrn_param);

  // optional .GET.ReLUParam relu_param = 14;
  inline bool has_relu_param() const;
  inline void clear_relu_param();
  static const int kReluParamFieldNumber = 14;
  inline const ::GET::ReLUParam& relu_param() const;
  inline ::GET::ReLUParam* mutable_relu_param();
  inline ::GET::ReLUParam* release_relu_param();
  inline void set_allocated_relu_param(::GET::ReLUParam* relu_param);

  // optional .GET.SigmoidParam sigmoid_param = 15;
  inline bool has_sigmoid_param() const;
  inline void clear_sigmoid_param();
  static const int kSigmoidParamFieldNumber = 15;
  inline const ::GET::SigmoidParam& sigmoid_param() const;
  inline ::GET::SigmoidParam* mutable_sigmoid_param();
  inline ::GET::SigmoidParam* release_sigmoid_param();
  inline void set_allocated_sigmoid_param(::GET::SigmoidParam* sigmoid_param);

  // @@protoc_insertion_point(class_scope:GET.TaskParam)
 private:
  inline void set_has_source_pos();
  inline void clear_has_source_pos();
  inline void set_has_result_pos();
  inline void clear_has_result_pos();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_add_param();
  inline void clear_has_add_param();
  inline void set_has_sub_param();
  inline void clear_has_sub_param();
  inline void set_has_mul_param();
  inline void clear_has_mul_param();
  inline void set_has_conv_param();
  inline void clear_has_conv_param();
  inline void set_has_pool_param();
  inline void clear_has_pool_param();
  inline void set_has_lrn_param();
  inline void clear_has_lrn_param();
  inline void set_has_relu_param();
  inline void clear_has_relu_param();
  inline void set_has_sigmoid_param();
  inline void clear_has_sigmoid_param();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> sourcef_;
  int source_pos_;
  int result_pos_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > sourcem_;
  ::google::protobuf::RepeatedPtrField< ::std::string> resultf_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > resultm_;
  ::GET::AddParam* add_param_;
  ::GET::SubParam* sub_param_;
  ::GET::MulParam* mul_param_;
  ::GET::ConvParam* conv_param_;
  ::GET::PoolParam* pool_param_;
  ::GET::LRNParam* lrn_param_;
  ::GET::ReLUParam* relu_param_;
  ::GET::SigmoidParam* sigmoid_param_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(15 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static TaskParam* default_instance_;
};
// -------------------------------------------------------------------

class AddParam : public ::google::protobuf::Message {
 public:
  AddParam();
  virtual ~AddParam();

  AddParam(const AddParam& from);

  inline AddParam& operator=(const AddParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddParam& default_instance();

  void Swap(AddParam* other);

  // implements Message ----------------------------------------------

  AddParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddParam& from);
  void MergeFrom(const AddParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 height = 1;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 1;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // optional int32 width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 channels = 3 [default = 1];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 3;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.AddParam)
 private:
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static AddParam* default_instance_;
};
// -------------------------------------------------------------------

class SubParam : public ::google::protobuf::Message {
 public:
  SubParam();
  virtual ~SubParam();

  SubParam(const SubParam& from);

  inline SubParam& operator=(const SubParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SubParam& default_instance();

  void Swap(SubParam* other);

  // implements Message ----------------------------------------------

  SubParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SubParam& from);
  void MergeFrom(const SubParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 height = 1;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 1;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // optional int32 width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 channels = 3 [default = 1];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 3;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.SubParam)
 private:
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static SubParam* default_instance_;
};
// -------------------------------------------------------------------

class MulParam : public ::google::protobuf::Message {
 public:
  MulParam();
  virtual ~MulParam();

  MulParam(const MulParam& from);

  inline MulParam& operator=(const MulParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MulParam& default_instance();

  void Swap(MulParam* other);

  // implements Message ----------------------------------------------

  MulParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MulParam& from);
  void MergeFrom(const MulParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 M = 1;
  inline bool has_m() const;
  inline void clear_m();
  static const int kMFieldNumber = 1;
  inline ::google::protobuf::int32 m() const;
  inline void set_m(::google::protobuf::int32 value);

  // optional int32 K = 2;
  inline bool has_k() const;
  inline void clear_k();
  static const int kKFieldNumber = 2;
  inline ::google::protobuf::int32 k() const;
  inline void set_k(::google::protobuf::int32 value);

  // optional int32 N = 3;
  inline bool has_n() const;
  inline void clear_n();
  static const int kNFieldNumber = 3;
  inline ::google::protobuf::int32 n() const;
  inline void set_n(::google::protobuf::int32 value);

  // optional int32 channels = 4 [default = 1];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 4;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.MulParam)
 private:
  inline void set_has_m();
  inline void clear_has_m();
  inline void set_has_k();
  inline void clear_has_k();
  inline void set_has_n();
  inline void clear_has_n();
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 m_;
  ::google::protobuf::int32 k_;
  ::google::protobuf::int32 n_;
  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static MulParam* default_instance_;
};
// -------------------------------------------------------------------

class ConvParam : public ::google::protobuf::Message {
 public:
  ConvParam();
  virtual ~ConvParam();

  ConvParam(const ConvParam& from);

  inline ConvParam& operator=(const ConvParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConvParam& default_instance();

  void Swap(ConvParam* other);

  // implements Message ----------------------------------------------

  ConvParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConvParam& from);
  void MergeFrom(const ConvParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 data_h = 1;
  inline bool has_data_h() const;
  inline void clear_data_h();
  static const int kDataHFieldNumber = 1;
  inline ::google::protobuf::int32 data_h() const;
  inline void set_data_h(::google::protobuf::int32 value);

  // optional int32 data_w = 2;
  inline bool has_data_w() const;
  inline void clear_data_w();
  static const int kDataWFieldNumber = 2;
  inline ::google::protobuf::int32 data_w() const;
  inline void set_data_w(::google::protobuf::int32 value);

  // optional int32 filter_h = 3;
  inline bool has_filter_h() const;
  inline void clear_filter_h();
  static const int kFilterHFieldNumber = 3;
  inline ::google::protobuf::int32 filter_h() const;
  inline void set_filter_h(::google::protobuf::int32 value);

  // optional int32 filter_w = 4;
  inline bool has_filter_w() const;
  inline void clear_filter_w();
  static const int kFilterWFieldNumber = 4;
  inline ::google::protobuf::int32 filter_w() const;
  inline void set_filter_w(::google::protobuf::int32 value);

  // optional int32 stride_h = 5 [default = 1];
  inline bool has_stride_h() const;
  inline void clear_stride_h();
  static const int kStrideHFieldNumber = 5;
  inline ::google::protobuf::int32 stride_h() const;
  inline void set_stride_h(::google::protobuf::int32 value);

  // optional int32 stride_w = 6 [default = 1];
  inline bool has_stride_w() const;
  inline void clear_stride_w();
  static const int kStrideWFieldNumber = 6;
  inline ::google::protobuf::int32 stride_w() const;
  inline void set_stride_w(::google::protobuf::int32 value);

  // optional int32 pad_h = 7 [default = 0];
  inline bool has_pad_h() const;
  inline void clear_pad_h();
  static const int kPadHFieldNumber = 7;
  inline ::google::protobuf::int32 pad_h() const;
  inline void set_pad_h(::google::protobuf::int32 value);

  // optional int32 pad_w = 8 [default = 0];
  inline bool has_pad_w() const;
  inline void clear_pad_w();
  static const int kPadWFieldNumber = 8;
  inline ::google::protobuf::int32 pad_w() const;
  inline void set_pad_w(::google::protobuf::int32 value);

  // optional int32 channels = 9 [default = 1];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 9;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.ConvParam)
 private:
  inline void set_has_data_h();
  inline void clear_has_data_h();
  inline void set_has_data_w();
  inline void clear_has_data_w();
  inline void set_has_filter_h();
  inline void clear_has_filter_h();
  inline void set_has_filter_w();
  inline void clear_has_filter_w();
  inline void set_has_stride_h();
  inline void clear_has_stride_h();
  inline void set_has_stride_w();
  inline void clear_has_stride_w();
  inline void set_has_pad_h();
  inline void clear_has_pad_h();
  inline void set_has_pad_w();
  inline void clear_has_pad_w();
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 data_h_;
  ::google::protobuf::int32 data_w_;
  ::google::protobuf::int32 filter_h_;
  ::google::protobuf::int32 filter_w_;
  ::google::protobuf::int32 stride_h_;
  ::google::protobuf::int32 stride_w_;
  ::google::protobuf::int32 pad_h_;
  ::google::protobuf::int32 pad_w_;
  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static ConvParam* default_instance_;
};
// -------------------------------------------------------------------

class PoolParam : public ::google::protobuf::Message {
 public:
  PoolParam();
  virtual ~PoolParam();

  PoolParam(const PoolParam& from);

  inline PoolParam& operator=(const PoolParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PoolParam& default_instance();

  void Swap(PoolParam* other);

  // implements Message ----------------------------------------------

  PoolParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PoolParam& from);
  void MergeFrom(const PoolParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 data_h = 1;
  inline bool has_data_h() const;
  inline void clear_data_h();
  static const int kDataHFieldNumber = 1;
  inline ::google::protobuf::int32 data_h() const;
  inline void set_data_h(::google::protobuf::int32 value);

  // optional int32 data_w = 2;
  inline bool has_data_w() const;
  inline void clear_data_w();
  static const int kDataWFieldNumber = 2;
  inline ::google::protobuf::int32 data_w() const;
  inline void set_data_w(::google::protobuf::int32 value);

  // optional int32 kernel_h = 3;
  inline bool has_kernel_h() const;
  inline void clear_kernel_h();
  static const int kKernelHFieldNumber = 3;
  inline ::google::protobuf::int32 kernel_h() const;
  inline void set_kernel_h(::google::protobuf::int32 value);

  // optional int32 kernel_w = 4;
  inline bool has_kernel_w() const;
  inline void clear_kernel_w();
  static const int kKernelWFieldNumber = 4;
  inline ::google::protobuf::int32 kernel_w() const;
  inline void set_kernel_w(::google::protobuf::int32 value);

  // optional int32 stride_h = 5 [default = 1];
  inline bool has_stride_h() const;
  inline void clear_stride_h();
  static const int kStrideHFieldNumber = 5;
  inline ::google::protobuf::int32 stride_h() const;
  inline void set_stride_h(::google::protobuf::int32 value);

  // optional int32 stride_w = 6 [default = 1];
  inline bool has_stride_w() const;
  inline void clear_stride_w();
  static const int kStrideWFieldNumber = 6;
  inline ::google::protobuf::int32 stride_w() const;
  inline void set_stride_w(::google::protobuf::int32 value);

  // optional int32 pad_h = 7 [default = 0];
  inline bool has_pad_h() const;
  inline void clear_pad_h();
  static const int kPadHFieldNumber = 7;
  inline ::google::protobuf::int32 pad_h() const;
  inline void set_pad_h(::google::protobuf::int32 value);

  // optional int32 pad_w = 8 [default = 0];
  inline bool has_pad_w() const;
  inline void clear_pad_w();
  static const int kPadWFieldNumber = 8;
  inline ::google::protobuf::int32 pad_w() const;
  inline void set_pad_w(::google::protobuf::int32 value);

  // optional int32 channels = 9 [default = 1];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 9;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.PoolParam)
 private:
  inline void set_has_data_h();
  inline void clear_has_data_h();
  inline void set_has_data_w();
  inline void clear_has_data_w();
  inline void set_has_kernel_h();
  inline void clear_has_kernel_h();
  inline void set_has_kernel_w();
  inline void clear_has_kernel_w();
  inline void set_has_stride_h();
  inline void clear_has_stride_h();
  inline void set_has_stride_w();
  inline void clear_has_stride_w();
  inline void set_has_pad_h();
  inline void clear_has_pad_h();
  inline void set_has_pad_w();
  inline void clear_has_pad_w();
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 data_h_;
  ::google::protobuf::int32 data_w_;
  ::google::protobuf::int32 kernel_h_;
  ::google::protobuf::int32 kernel_w_;
  ::google::protobuf::int32 stride_h_;
  ::google::protobuf::int32 stride_w_;
  ::google::protobuf::int32 pad_h_;
  ::google::protobuf::int32 pad_w_;
  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static PoolParam* default_instance_;
};
// -------------------------------------------------------------------

class LRNParam : public ::google::protobuf::Message {
 public:
  LRNParam();
  virtual ~LRNParam();

  LRNParam(const LRNParam& from);

  inline LRNParam& operator=(const LRNParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LRNParam& default_instance();

  void Swap(LRNParam* other);

  // implements Message ----------------------------------------------

  LRNParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LRNParam& from);
  void MergeFrom(const LRNParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 channels = 1 [default = 0];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 1;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.LRNParam)
 private:
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static LRNParam* default_instance_;
};
// -------------------------------------------------------------------

class ReLUParam : public ::google::protobuf::Message {
 public:
  ReLUParam();
  virtual ~ReLUParam();

  ReLUParam(const ReLUParam& from);

  inline ReLUParam& operator=(const ReLUParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReLUParam& default_instance();

  void Swap(ReLUParam* other);

  // implements Message ----------------------------------------------

  ReLUParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReLUParam& from);
  void MergeFrom(const ReLUParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 height = 1 [default = 1];
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 1;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // optional int32 width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 channels = 3 [default = 1];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 3;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.ReLUParam)
 private:
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static ReLUParam* default_instance_;
};
// -------------------------------------------------------------------

class SigmoidParam : public ::google::protobuf::Message {
 public:
  SigmoidParam();
  virtual ~SigmoidParam();

  SigmoidParam(const SigmoidParam& from);

  inline SigmoidParam& operator=(const SigmoidParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SigmoidParam& default_instance();

  void Swap(SigmoidParam* other);

  // implements Message ----------------------------------------------

  SigmoidParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SigmoidParam& from);
  void MergeFrom(const SigmoidParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 height = 1 [default = 1];
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 1;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // optional int32 width = 2;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 2;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 channels = 3 [default = 1];
  inline bool has_channels() const;
  inline void clear_channels();
  static const int kChannelsFieldNumber = 3;
  inline ::google::protobuf::int32 channels() const;
  inline void set_channels(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GET.SigmoidParam)
 private:
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_channels();
  inline void clear_has_channels();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 channels_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_GET_2eproto();
  friend void protobuf_AssignDesc_GET_2eproto();
  friend void protobuf_ShutdownFile_GET_2eproto();

  void InitAsDefaultInstance();
  static SigmoidParam* default_instance_;
};
// ===================================================================


// ===================================================================

// TaskParam

// optional .GET.TaskParam.DataPosition source_pos = 1 [default = HOSTMEM];
inline bool TaskParam::has_source_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskParam::set_has_source_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskParam::clear_has_source_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskParam::clear_source_pos() {
  source_pos_ = 1;
  clear_has_source_pos();
}
inline ::GET::TaskParam_DataPosition TaskParam::source_pos() const {
  return static_cast< ::GET::TaskParam_DataPosition >(source_pos_);
}
inline void TaskParam::set_source_pos(::GET::TaskParam_DataPosition value) {
  assert(::GET::TaskParam_DataPosition_IsValid(value));
  set_has_source_pos();
  source_pos_ = value;
}

// repeated string sourcef = 2;
inline int TaskParam::sourcef_size() const {
  return sourcef_.size();
}
inline void TaskParam::clear_sourcef() {
  sourcef_.Clear();
}
inline const ::std::string& TaskParam::sourcef(int index) const {
  return sourcef_.Get(index);
}
inline ::std::string* TaskParam::mutable_sourcef(int index) {
  return sourcef_.Mutable(index);
}
inline void TaskParam::set_sourcef(int index, const ::std::string& value) {
  sourcef_.Mutable(index)->assign(value);
}
inline void TaskParam::set_sourcef(int index, const char* value) {
  sourcef_.Mutable(index)->assign(value);
}
inline void TaskParam::set_sourcef(int index, const char* value, size_t size) {
  sourcef_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskParam::add_sourcef() {
  return sourcef_.Add();
}
inline void TaskParam::add_sourcef(const ::std::string& value) {
  sourcef_.Add()->assign(value);
}
inline void TaskParam::add_sourcef(const char* value) {
  sourcef_.Add()->assign(value);
}
inline void TaskParam::add_sourcef(const char* value, size_t size) {
  sourcef_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TaskParam::sourcef() const {
  return sourcef_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TaskParam::mutable_sourcef() {
  return &sourcef_;
}

// repeated uint64 sourcem = 3;
inline int TaskParam::sourcem_size() const {
  return sourcem_.size();
}
inline void TaskParam::clear_sourcem() {
  sourcem_.Clear();
}
inline ::google::protobuf::uint64 TaskParam::sourcem(int index) const {
  return sourcem_.Get(index);
}
inline void TaskParam::set_sourcem(int index, ::google::protobuf::uint64 value) {
  sourcem_.Set(index, value);
}
inline void TaskParam::add_sourcem(::google::protobuf::uint64 value) {
  sourcem_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
TaskParam::sourcem() const {
  return sourcem_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
TaskParam::mutable_sourcem() {
  return &sourcem_;
}

// optional .GET.TaskParam.DataPosition result_pos = 4 [default = HOSTMEM];
inline bool TaskParam::has_result_pos() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TaskParam::set_has_result_pos() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TaskParam::clear_has_result_pos() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TaskParam::clear_result_pos() {
  result_pos_ = 1;
  clear_has_result_pos();
}
inline ::GET::TaskParam_DataPosition TaskParam::result_pos() const {
  return static_cast< ::GET::TaskParam_DataPosition >(result_pos_);
}
inline void TaskParam::set_result_pos(::GET::TaskParam_DataPosition value) {
  assert(::GET::TaskParam_DataPosition_IsValid(value));
  set_has_result_pos();
  result_pos_ = value;
}

// repeated string resultf = 5;
inline int TaskParam::resultf_size() const {
  return resultf_.size();
}
inline void TaskParam::clear_resultf() {
  resultf_.Clear();
}
inline const ::std::string& TaskParam::resultf(int index) const {
  return resultf_.Get(index);
}
inline ::std::string* TaskParam::mutable_resultf(int index) {
  return resultf_.Mutable(index);
}
inline void TaskParam::set_resultf(int index, const ::std::string& value) {
  resultf_.Mutable(index)->assign(value);
}
inline void TaskParam::set_resultf(int index, const char* value) {
  resultf_.Mutable(index)->assign(value);
}
inline void TaskParam::set_resultf(int index, const char* value, size_t size) {
  resultf_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskParam::add_resultf() {
  return resultf_.Add();
}
inline void TaskParam::add_resultf(const ::std::string& value) {
  resultf_.Add()->assign(value);
}
inline void TaskParam::add_resultf(const char* value) {
  resultf_.Add()->assign(value);
}
inline void TaskParam::add_resultf(const char* value, size_t size) {
  resultf_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TaskParam::resultf() const {
  return resultf_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TaskParam::mutable_resultf() {
  return &resultf_;
}

// repeated uint64 resultm = 6;
inline int TaskParam::resultm_size() const {
  return resultm_.size();
}
inline void TaskParam::clear_resultm() {
  resultm_.Clear();
}
inline ::google::protobuf::uint64 TaskParam::resultm(int index) const {
  return resultm_.Get(index);
}
inline void TaskParam::set_resultm(int index, ::google::protobuf::uint64 value) {
  resultm_.Set(index, value);
}
inline void TaskParam::add_resultm(::google::protobuf::uint64 value) {
  resultm_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
TaskParam::resultm() const {
  return resultm_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
TaskParam::mutable_resultm() {
  return &resultm_;
}

// optional .GET.TaskParam.TaskType type = 7;
inline bool TaskParam::has_type() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TaskParam::set_has_type() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TaskParam::clear_has_type() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TaskParam::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::GET::TaskParam_TaskType TaskParam::type() const {
  return static_cast< ::GET::TaskParam_TaskType >(type_);
}
inline void TaskParam::set_type(::GET::TaskParam_TaskType value) {
  assert(::GET::TaskParam_TaskType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional .GET.AddParam add_param = 8;
inline bool TaskParam::has_add_param() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TaskParam::set_has_add_param() {
  _has_bits_[0] |= 0x00000080u;
}
inline void TaskParam::clear_has_add_param() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void TaskParam::clear_add_param() {
  if (add_param_ != NULL) add_param_->::GET::AddParam::Clear();
  clear_has_add_param();
}
inline const ::GET::AddParam& TaskParam::add_param() const {
  return add_param_ != NULL ? *add_param_ : *default_instance_->add_param_;
}
inline ::GET::AddParam* TaskParam::mutable_add_param() {
  set_has_add_param();
  if (add_param_ == NULL) add_param_ = new ::GET::AddParam;
  return add_param_;
}
inline ::GET::AddParam* TaskParam::release_add_param() {
  clear_has_add_param();
  ::GET::AddParam* temp = add_param_;
  add_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_add_param(::GET::AddParam* add_param) {
  delete add_param_;
  add_param_ = add_param;
  if (add_param) {
    set_has_add_param();
  } else {
    clear_has_add_param();
  }
}

// optional .GET.SubParam sub_param = 9;
inline bool TaskParam::has_sub_param() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void TaskParam::set_has_sub_param() {
  _has_bits_[0] |= 0x00000100u;
}
inline void TaskParam::clear_has_sub_param() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void TaskParam::clear_sub_param() {
  if (sub_param_ != NULL) sub_param_->::GET::SubParam::Clear();
  clear_has_sub_param();
}
inline const ::GET::SubParam& TaskParam::sub_param() const {
  return sub_param_ != NULL ? *sub_param_ : *default_instance_->sub_param_;
}
inline ::GET::SubParam* TaskParam::mutable_sub_param() {
  set_has_sub_param();
  if (sub_param_ == NULL) sub_param_ = new ::GET::SubParam;
  return sub_param_;
}
inline ::GET::SubParam* TaskParam::release_sub_param() {
  clear_has_sub_param();
  ::GET::SubParam* temp = sub_param_;
  sub_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_sub_param(::GET::SubParam* sub_param) {
  delete sub_param_;
  sub_param_ = sub_param;
  if (sub_param) {
    set_has_sub_param();
  } else {
    clear_has_sub_param();
  }
}

// optional .GET.MulParam mul_param = 10;
inline bool TaskParam::has_mul_param() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void TaskParam::set_has_mul_param() {
  _has_bits_[0] |= 0x00000200u;
}
inline void TaskParam::clear_has_mul_param() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void TaskParam::clear_mul_param() {
  if (mul_param_ != NULL) mul_param_->::GET::MulParam::Clear();
  clear_has_mul_param();
}
inline const ::GET::MulParam& TaskParam::mul_param() const {
  return mul_param_ != NULL ? *mul_param_ : *default_instance_->mul_param_;
}
inline ::GET::MulParam* TaskParam::mutable_mul_param() {
  set_has_mul_param();
  if (mul_param_ == NULL) mul_param_ = new ::GET::MulParam;
  return mul_param_;
}
inline ::GET::MulParam* TaskParam::release_mul_param() {
  clear_has_mul_param();
  ::GET::MulParam* temp = mul_param_;
  mul_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_mul_param(::GET::MulParam* mul_param) {
  delete mul_param_;
  mul_param_ = mul_param;
  if (mul_param) {
    set_has_mul_param();
  } else {
    clear_has_mul_param();
  }
}

// optional .GET.ConvParam conv_param = 11;
inline bool TaskParam::has_conv_param() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void TaskParam::set_has_conv_param() {
  _has_bits_[0] |= 0x00000400u;
}
inline void TaskParam::clear_has_conv_param() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void TaskParam::clear_conv_param() {
  if (conv_param_ != NULL) conv_param_->::GET::ConvParam::Clear();
  clear_has_conv_param();
}
inline const ::GET::ConvParam& TaskParam::conv_param() const {
  return conv_param_ != NULL ? *conv_param_ : *default_instance_->conv_param_;
}
inline ::GET::ConvParam* TaskParam::mutable_conv_param() {
  set_has_conv_param();
  if (conv_param_ == NULL) conv_param_ = new ::GET::ConvParam;
  return conv_param_;
}
inline ::GET::ConvParam* TaskParam::release_conv_param() {
  clear_has_conv_param();
  ::GET::ConvParam* temp = conv_param_;
  conv_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_conv_param(::GET::ConvParam* conv_param) {
  delete conv_param_;
  conv_param_ = conv_param;
  if (conv_param) {
    set_has_conv_param();
  } else {
    clear_has_conv_param();
  }
}

// optional .GET.PoolParam pool_param = 12;
inline bool TaskParam::has_pool_param() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void TaskParam::set_has_pool_param() {
  _has_bits_[0] |= 0x00000800u;
}
inline void TaskParam::clear_has_pool_param() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void TaskParam::clear_pool_param() {
  if (pool_param_ != NULL) pool_param_->::GET::PoolParam::Clear();
  clear_has_pool_param();
}
inline const ::GET::PoolParam& TaskParam::pool_param() const {
  return pool_param_ != NULL ? *pool_param_ : *default_instance_->pool_param_;
}
inline ::GET::PoolParam* TaskParam::mutable_pool_param() {
  set_has_pool_param();
  if (pool_param_ == NULL) pool_param_ = new ::GET::PoolParam;
  return pool_param_;
}
inline ::GET::PoolParam* TaskParam::release_pool_param() {
  clear_has_pool_param();
  ::GET::PoolParam* temp = pool_param_;
  pool_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_pool_param(::GET::PoolParam* pool_param) {
  delete pool_param_;
  pool_param_ = pool_param;
  if (pool_param) {
    set_has_pool_param();
  } else {
    clear_has_pool_param();
  }
}

// optional .GET.LRNParam lrn_param = 13;
inline bool TaskParam::has_lrn_param() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void TaskParam::set_has_lrn_param() {
  _has_bits_[0] |= 0x00001000u;
}
inline void TaskParam::clear_has_lrn_param() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void TaskParam::clear_lrn_param() {
  if (lrn_param_ != NULL) lrn_param_->::GET::LRNParam::Clear();
  clear_has_lrn_param();
}
inline const ::GET::LRNParam& TaskParam::lrn_param() const {
  return lrn_param_ != NULL ? *lrn_param_ : *default_instance_->lrn_param_;
}
inline ::GET::LRNParam* TaskParam::mutable_lrn_param() {
  set_has_lrn_param();
  if (lrn_param_ == NULL) lrn_param_ = new ::GET::LRNParam;
  return lrn_param_;
}
inline ::GET::LRNParam* TaskParam::release_lrn_param() {
  clear_has_lrn_param();
  ::GET::LRNParam* temp = lrn_param_;
  lrn_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_lrn_param(::GET::LRNParam* lrn_param) {
  delete lrn_param_;
  lrn_param_ = lrn_param;
  if (lrn_param) {
    set_has_lrn_param();
  } else {
    clear_has_lrn_param();
  }
}

// optional .GET.ReLUParam relu_param = 14;
inline bool TaskParam::has_relu_param() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void TaskParam::set_has_relu_param() {
  _has_bits_[0] |= 0x00002000u;
}
inline void TaskParam::clear_has_relu_param() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void TaskParam::clear_relu_param() {
  if (relu_param_ != NULL) relu_param_->::GET::ReLUParam::Clear();
  clear_has_relu_param();
}
inline const ::GET::ReLUParam& TaskParam::relu_param() const {
  return relu_param_ != NULL ? *relu_param_ : *default_instance_->relu_param_;
}
inline ::GET::ReLUParam* TaskParam::mutable_relu_param() {
  set_has_relu_param();
  if (relu_param_ == NULL) relu_param_ = new ::GET::ReLUParam;
  return relu_param_;
}
inline ::GET::ReLUParam* TaskParam::release_relu_param() {
  clear_has_relu_param();
  ::GET::ReLUParam* temp = relu_param_;
  relu_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_relu_param(::GET::ReLUParam* relu_param) {
  delete relu_param_;
  relu_param_ = relu_param;
  if (relu_param) {
    set_has_relu_param();
  } else {
    clear_has_relu_param();
  }
}

// optional .GET.SigmoidParam sigmoid_param = 15;
inline bool TaskParam::has_sigmoid_param() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void TaskParam::set_has_sigmoid_param() {
  _has_bits_[0] |= 0x00004000u;
}
inline void TaskParam::clear_has_sigmoid_param() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void TaskParam::clear_sigmoid_param() {
  if (sigmoid_param_ != NULL) sigmoid_param_->::GET::SigmoidParam::Clear();
  clear_has_sigmoid_param();
}
inline const ::GET::SigmoidParam& TaskParam::sigmoid_param() const {
  return sigmoid_param_ != NULL ? *sigmoid_param_ : *default_instance_->sigmoid_param_;
}
inline ::GET::SigmoidParam* TaskParam::mutable_sigmoid_param() {
  set_has_sigmoid_param();
  if (sigmoid_param_ == NULL) sigmoid_param_ = new ::GET::SigmoidParam;
  return sigmoid_param_;
}
inline ::GET::SigmoidParam* TaskParam::release_sigmoid_param() {
  clear_has_sigmoid_param();
  ::GET::SigmoidParam* temp = sigmoid_param_;
  sigmoid_param_ = NULL;
  return temp;
}
inline void TaskParam::set_allocated_sigmoid_param(::GET::SigmoidParam* sigmoid_param) {
  delete sigmoid_param_;
  sigmoid_param_ = sigmoid_param;
  if (sigmoid_param) {
    set_has_sigmoid_param();
  } else {
    clear_has_sigmoid_param();
  }
}

// -------------------------------------------------------------------

// AddParam

// optional int32 height = 1;
inline bool AddParam::has_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AddParam::set_has_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AddParam::clear_has_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AddParam::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 AddParam::height() const {
  return height_;
}
inline void AddParam::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
}

// optional int32 width = 2;
inline bool AddParam::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AddParam::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AddParam::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AddParam::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 AddParam::width() const {
  return width_;
}
inline void AddParam::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
}

// optional int32 channels = 3 [default = 1];
inline bool AddParam::has_channels() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AddParam::set_has_channels() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AddParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AddParam::clear_channels() {
  channels_ = 1;
  clear_has_channels();
}
inline ::google::protobuf::int32 AddParam::channels() const {
  return channels_;
}
inline void AddParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}

// -------------------------------------------------------------------

// SubParam

// optional int32 height = 1;
inline bool SubParam::has_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SubParam::set_has_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SubParam::clear_has_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SubParam::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 SubParam::height() const {
  return height_;
}
inline void SubParam::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
}

// optional int32 width = 2;
inline bool SubParam::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SubParam::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SubParam::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SubParam::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 SubParam::width() const {
  return width_;
}
inline void SubParam::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
}

// optional int32 channels = 3 [default = 1];
inline bool SubParam::has_channels() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SubParam::set_has_channels() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SubParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SubParam::clear_channels() {
  channels_ = 1;
  clear_has_channels();
}
inline ::google::protobuf::int32 SubParam::channels() const {
  return channels_;
}
inline void SubParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}

// -------------------------------------------------------------------

// MulParam

// optional int32 M = 1;
inline bool MulParam::has_m() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MulParam::set_has_m() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MulParam::clear_has_m() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MulParam::clear_m() {
  m_ = 0;
  clear_has_m();
}
inline ::google::protobuf::int32 MulParam::m() const {
  return m_;
}
inline void MulParam::set_m(::google::protobuf::int32 value) {
  set_has_m();
  m_ = value;
}

// optional int32 K = 2;
inline bool MulParam::has_k() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MulParam::set_has_k() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MulParam::clear_has_k() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MulParam::clear_k() {
  k_ = 0;
  clear_has_k();
}
inline ::google::protobuf::int32 MulParam::k() const {
  return k_;
}
inline void MulParam::set_k(::google::protobuf::int32 value) {
  set_has_k();
  k_ = value;
}

// optional int32 N = 3;
inline bool MulParam::has_n() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MulParam::set_has_n() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MulParam::clear_has_n() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MulParam::clear_n() {
  n_ = 0;
  clear_has_n();
}
inline ::google::protobuf::int32 MulParam::n() const {
  return n_;
}
inline void MulParam::set_n(::google::protobuf::int32 value) {
  set_has_n();
  n_ = value;
}

// optional int32 channels = 4 [default = 1];
inline bool MulParam::has_channels() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MulParam::set_has_channels() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MulParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MulParam::clear_channels() {
  channels_ = 1;
  clear_has_channels();
}
inline ::google::protobuf::int32 MulParam::channels() const {
  return channels_;
}
inline void MulParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}

// -------------------------------------------------------------------

// ConvParam

// optional int32 data_h = 1;
inline bool ConvParam::has_data_h() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConvParam::set_has_data_h() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConvParam::clear_has_data_h() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConvParam::clear_data_h() {
  data_h_ = 0;
  clear_has_data_h();
}
inline ::google::protobuf::int32 ConvParam::data_h() const {
  return data_h_;
}
inline void ConvParam::set_data_h(::google::protobuf::int32 value) {
  set_has_data_h();
  data_h_ = value;
}

// optional int32 data_w = 2;
inline bool ConvParam::has_data_w() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConvParam::set_has_data_w() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConvParam::clear_has_data_w() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConvParam::clear_data_w() {
  data_w_ = 0;
  clear_has_data_w();
}
inline ::google::protobuf::int32 ConvParam::data_w() const {
  return data_w_;
}
inline void ConvParam::set_data_w(::google::protobuf::int32 value) {
  set_has_data_w();
  data_w_ = value;
}

// optional int32 filter_h = 3;
inline bool ConvParam::has_filter_h() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ConvParam::set_has_filter_h() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ConvParam::clear_has_filter_h() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ConvParam::clear_filter_h() {
  filter_h_ = 0;
  clear_has_filter_h();
}
inline ::google::protobuf::int32 ConvParam::filter_h() const {
  return filter_h_;
}
inline void ConvParam::set_filter_h(::google::protobuf::int32 value) {
  set_has_filter_h();
  filter_h_ = value;
}

// optional int32 filter_w = 4;
inline bool ConvParam::has_filter_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ConvParam::set_has_filter_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ConvParam::clear_has_filter_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ConvParam::clear_filter_w() {
  filter_w_ = 0;
  clear_has_filter_w();
}
inline ::google::protobuf::int32 ConvParam::filter_w() const {
  return filter_w_;
}
inline void ConvParam::set_filter_w(::google::protobuf::int32 value) {
  set_has_filter_w();
  filter_w_ = value;
}

// optional int32 stride_h = 5 [default = 1];
inline bool ConvParam::has_stride_h() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ConvParam::set_has_stride_h() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ConvParam::clear_has_stride_h() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ConvParam::clear_stride_h() {
  stride_h_ = 1;
  clear_has_stride_h();
}
inline ::google::protobuf::int32 ConvParam::stride_h() const {
  return stride_h_;
}
inline void ConvParam::set_stride_h(::google::protobuf::int32 value) {
  set_has_stride_h();
  stride_h_ = value;
}

// optional int32 stride_w = 6 [default = 1];
inline bool ConvParam::has_stride_w() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ConvParam::set_has_stride_w() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ConvParam::clear_has_stride_w() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ConvParam::clear_stride_w() {
  stride_w_ = 1;
  clear_has_stride_w();
}
inline ::google::protobuf::int32 ConvParam::stride_w() const {
  return stride_w_;
}
inline void ConvParam::set_stride_w(::google::protobuf::int32 value) {
  set_has_stride_w();
  stride_w_ = value;
}

// optional int32 pad_h = 7 [default = 0];
inline bool ConvParam::has_pad_h() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ConvParam::set_has_pad_h() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ConvParam::clear_has_pad_h() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ConvParam::clear_pad_h() {
  pad_h_ = 0;
  clear_has_pad_h();
}
inline ::google::protobuf::int32 ConvParam::pad_h() const {
  return pad_h_;
}
inline void ConvParam::set_pad_h(::google::protobuf::int32 value) {
  set_has_pad_h();
  pad_h_ = value;
}

// optional int32 pad_w = 8 [default = 0];
inline bool ConvParam::has_pad_w() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ConvParam::set_has_pad_w() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ConvParam::clear_has_pad_w() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ConvParam::clear_pad_w() {
  pad_w_ = 0;
  clear_has_pad_w();
}
inline ::google::protobuf::int32 ConvParam::pad_w() const {
  return pad_w_;
}
inline void ConvParam::set_pad_w(::google::protobuf::int32 value) {
  set_has_pad_w();
  pad_w_ = value;
}

// optional int32 channels = 9 [default = 1];
inline bool ConvParam::has_channels() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ConvParam::set_has_channels() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ConvParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ConvParam::clear_channels() {
  channels_ = 1;
  clear_has_channels();
}
inline ::google::protobuf::int32 ConvParam::channels() const {
  return channels_;
}
inline void ConvParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}

// -------------------------------------------------------------------

// PoolParam

// optional int32 data_h = 1;
inline bool PoolParam::has_data_h() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PoolParam::set_has_data_h() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PoolParam::clear_has_data_h() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PoolParam::clear_data_h() {
  data_h_ = 0;
  clear_has_data_h();
}
inline ::google::protobuf::int32 PoolParam::data_h() const {
  return data_h_;
}
inline void PoolParam::set_data_h(::google::protobuf::int32 value) {
  set_has_data_h();
  data_h_ = value;
}

// optional int32 data_w = 2;
inline bool PoolParam::has_data_w() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PoolParam::set_has_data_w() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PoolParam::clear_has_data_w() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PoolParam::clear_data_w() {
  data_w_ = 0;
  clear_has_data_w();
}
inline ::google::protobuf::int32 PoolParam::data_w() const {
  return data_w_;
}
inline void PoolParam::set_data_w(::google::protobuf::int32 value) {
  set_has_data_w();
  data_w_ = value;
}

// optional int32 kernel_h = 3;
inline bool PoolParam::has_kernel_h() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PoolParam::set_has_kernel_h() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PoolParam::clear_has_kernel_h() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PoolParam::clear_kernel_h() {
  kernel_h_ = 0;
  clear_has_kernel_h();
}
inline ::google::protobuf::int32 PoolParam::kernel_h() const {
  return kernel_h_;
}
inline void PoolParam::set_kernel_h(::google::protobuf::int32 value) {
  set_has_kernel_h();
  kernel_h_ = value;
}

// optional int32 kernel_w = 4;
inline bool PoolParam::has_kernel_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PoolParam::set_has_kernel_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PoolParam::clear_has_kernel_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PoolParam::clear_kernel_w() {
  kernel_w_ = 0;
  clear_has_kernel_w();
}
inline ::google::protobuf::int32 PoolParam::kernel_w() const {
  return kernel_w_;
}
inline void PoolParam::set_kernel_w(::google::protobuf::int32 value) {
  set_has_kernel_w();
  kernel_w_ = value;
}

// optional int32 stride_h = 5 [default = 1];
inline bool PoolParam::has_stride_h() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PoolParam::set_has_stride_h() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PoolParam::clear_has_stride_h() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PoolParam::clear_stride_h() {
  stride_h_ = 1;
  clear_has_stride_h();
}
inline ::google::protobuf::int32 PoolParam::stride_h() const {
  return stride_h_;
}
inline void PoolParam::set_stride_h(::google::protobuf::int32 value) {
  set_has_stride_h();
  stride_h_ = value;
}

// optional int32 stride_w = 6 [default = 1];
inline bool PoolParam::has_stride_w() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PoolParam::set_has_stride_w() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PoolParam::clear_has_stride_w() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PoolParam::clear_stride_w() {
  stride_w_ = 1;
  clear_has_stride_w();
}
inline ::google::protobuf::int32 PoolParam::stride_w() const {
  return stride_w_;
}
inline void PoolParam::set_stride_w(::google::protobuf::int32 value) {
  set_has_stride_w();
  stride_w_ = value;
}

// optional int32 pad_h = 7 [default = 0];
inline bool PoolParam::has_pad_h() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PoolParam::set_has_pad_h() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PoolParam::clear_has_pad_h() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PoolParam::clear_pad_h() {
  pad_h_ = 0;
  clear_has_pad_h();
}
inline ::google::protobuf::int32 PoolParam::pad_h() const {
  return pad_h_;
}
inline void PoolParam::set_pad_h(::google::protobuf::int32 value) {
  set_has_pad_h();
  pad_h_ = value;
}

// optional int32 pad_w = 8 [default = 0];
inline bool PoolParam::has_pad_w() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PoolParam::set_has_pad_w() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PoolParam::clear_has_pad_w() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PoolParam::clear_pad_w() {
  pad_w_ = 0;
  clear_has_pad_w();
}
inline ::google::protobuf::int32 PoolParam::pad_w() const {
  return pad_w_;
}
inline void PoolParam::set_pad_w(::google::protobuf::int32 value) {
  set_has_pad_w();
  pad_w_ = value;
}

// optional int32 channels = 9 [default = 1];
inline bool PoolParam::has_channels() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PoolParam::set_has_channels() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PoolParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PoolParam::clear_channels() {
  channels_ = 1;
  clear_has_channels();
}
inline ::google::protobuf::int32 PoolParam::channels() const {
  return channels_;
}
inline void PoolParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}

// -------------------------------------------------------------------

// LRNParam

// optional int32 channels = 1 [default = 0];
inline bool LRNParam::has_channels() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LRNParam::set_has_channels() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LRNParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LRNParam::clear_channels() {
  channels_ = 0;
  clear_has_channels();
}
inline ::google::protobuf::int32 LRNParam::channels() const {
  return channels_;
}
inline void LRNParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}

// -------------------------------------------------------------------

// ReLUParam

// optional int32 height = 1 [default = 1];
inline bool ReLUParam::has_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReLUParam::set_has_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReLUParam::clear_has_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReLUParam::clear_height() {
  height_ = 1;
  clear_has_height();
}
inline ::google::protobuf::int32 ReLUParam::height() const {
  return height_;
}
inline void ReLUParam::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
}

// optional int32 width = 2;
inline bool ReLUParam::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReLUParam::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReLUParam::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReLUParam::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 ReLUParam::width() const {
  return width_;
}
inline void ReLUParam::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
}

// optional int32 channels = 3 [default = 1];
inline bool ReLUParam::has_channels() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReLUParam::set_has_channels() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ReLUParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ReLUParam::clear_channels() {
  channels_ = 1;
  clear_has_channels();
}
inline ::google::protobuf::int32 ReLUParam::channels() const {
  return channels_;
}
inline void ReLUParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}

// -------------------------------------------------------------------

// SigmoidParam

// optional int32 height = 1 [default = 1];
inline bool SigmoidParam::has_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SigmoidParam::set_has_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SigmoidParam::clear_has_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SigmoidParam::clear_height() {
  height_ = 1;
  clear_has_height();
}
inline ::google::protobuf::int32 SigmoidParam::height() const {
  return height_;
}
inline void SigmoidParam::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
}

// optional int32 width = 2;
inline bool SigmoidParam::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SigmoidParam::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SigmoidParam::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SigmoidParam::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 SigmoidParam::width() const {
  return width_;
}
inline void SigmoidParam::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
}

// optional int32 channels = 3 [default = 1];
inline bool SigmoidParam::has_channels() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SigmoidParam::set_has_channels() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SigmoidParam::clear_has_channels() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SigmoidParam::clear_channels() {
  channels_ = 1;
  clear_has_channels();
}
inline ::google::protobuf::int32 SigmoidParam::channels() const {
  return channels_;
}
inline void SigmoidParam::set_channels(::google::protobuf::int32 value) {
  set_has_channels();
  channels_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GET

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GET::TaskParam_DataPosition>() {
  return ::GET::TaskParam_DataPosition_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GET::TaskParam_TaskType>() {
  return ::GET::TaskParam_TaskType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GET_2eproto__INCLUDED
